//! Deterministic Gaming Intelligence query/control services.
//!
//! No recommendation is generated by a model. A bundled, versioned knowledge
//! pack evaluates an allowlisted set of observed conditions. Mutations are
//! typed, consent-bound, recorded with exact before-state, verified after each
//! step, and rolled back in reverse order on failure.

#![cfg(windows)]
// Tonic's rich Status value is intentionally returned by these private RPC
// helpers so metadata and transport semantics are preserved at the boundary.
#![allow(clippy::result_large_err)]

mod frame_capture;

use std::collections::HashMap;
use std::path::Path;
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::sync::{Arc, Mutex};
use std::thread::JoinHandle;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use tonic::{Request, Response, Status};

use atlas_collectors::{
    battery_status, device_info, discover_games, get_power_overlay_state, power_is_ac,
    primary_display, restore_power_overlay_state, set_power_overlay, DiscoveredGame,
    DiscoveredGamePlatform, DiscoveredGameSupportLevel,
};
use atlas_ipc::transport::PipeConnectInfo;
use atlas_ipc::v0::atlas_gaming_control_server::AtlasGamingControl;
use atlas_ipc::v0::atlas_gaming_query_server::AtlasGamingQuery;
use atlas_ipc::v0::*;
use atlas_store::{
    GameInstallRow, GameSessionRow, GameTraceBucketRow, GamingPlanRow, GamingPlanStepRow,
};

use frame_capture::{FrameCaptureSummary, PresentMonCapture, VALIDATION_LIMITATION};

use crate::ipc::{QueryService, SharedStore};

const KNOWLEDGE_JSON: &str = include_str!("../knowledge/gaming-pack-v1.json");
const TOKEN_TTL_MS: i64 = 5 * 60 * 1000;
const NO_FRAME_TIME_LIMITATION: &str = "This session contains no measured frame data, so Atlas cannot report FPS or frame-time pacing for it.";

#[derive(Debug, Deserialize)]
struct KnowledgePack {
    version: String,
    reviewed_date: String,
    rules: Vec<KnowledgeRule>,
    blocked_actions: Vec<String>,
}

#[derive(Debug, Deserialize)]
struct KnowledgeRule {
    id: String,
    catalog_ids: Vec<String>,
    condition: String,
    severity: String,
    title: String,
    observed: String,
    why_it_matters: String,
    expected_benefit: String,
    tradeoff: String,
    risk_lane: String,
    action_key: String,
    restart_requirement: String,
    rollback: String,
    verification: String,
    sources: Vec<KnowledgeSource>,
}

#[derive(Debug, Deserialize)]
struct KnowledgeSource {
    title: String,
    uri: String,
    publisher: String,
    reviewed_date: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct StoredInstallPayload {
    limitations: Vec<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
struct StoredSessionPayload {
    frame_summary: Option<FrameCaptureSummary>,
    limitations: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct StoredPlanPayload {
    game_name: String,
    source_finding_ids: Vec<String>,
    limitations: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct StoredStepPayload {
    title: String,
    explanation: String,
    before_value: String,
    after_value: String,
    temporary: bool,
    scope: String,
    restart_requirement: String,
    rollback: String,
    verification: String,
    preconditions: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct PowerBeforeState {
    guid: String,
    label: String,
}

#[derive(Debug, Clone)]
struct PreparedToken {
    plan_id: i64,
    plan_hash: String,
    config_hash: String,
    client_sid: String,
    expires_ms: i64,
}

struct ActiveSession {
    stop: Arc<AtomicBool>,
    handle: Option<JoinHandle<()>>,
}

pub struct GamingService {
    query: Arc<QueryService>,
    store: SharedStore,
    pack: KnowledgePack,
    tokens: Mutex<HashMap<String, PreparedToken>>,
    token_counter: AtomicU64,
    token_secret: [u8; 32],
    sessions: Mutex<HashMap<i64, ActiveSession>>,
}

impl GamingService {
    pub fn new(query: Arc<QueryService>) -> anyhow::Result<Self> {
        let pack: KnowledgePack = serde_json::from_str(KNOWLEDGE_JSON)?;
        if pack.version.trim().is_empty() || pack.reviewed_date.trim().is_empty() {
            anyhow::bail!("gaming knowledge pack is missing version metadata");
        }
        let mut hasher = Sha256::new();
        hasher.update(now_ms().to_le_bytes());
        hasher.update(std::process::id().to_le_bytes());
        hasher.update(KNOWLEDGE_JSON.as_bytes());
        let token_secret: [u8; 32] = hasher.finalize().into();
        let store = query.store();
        let service = Self {
            query,
            store,
            pack,
            tokens: Mutex::new(HashMap::new()),
            token_counter: AtomicU64::new(1),
            token_secret,
            sessions: Mutex::new(HashMap::new()),
        };
        service.recover_incomplete_plans();
        Ok(service)
    }

    fn recover_incomplete_plans(&self) {
        let plans = self
            .store
            .lock()
            .ok()
            .and_then(|store| {
                store
                    .list_gaming_plans_with_statuses(&[
                        GamingPlanStatus::Applying as i32,
                        GamingPlanStatus::RollingBack as i32,
                    ])
                    .ok()
            })
            .unwrap_or_default();
        for plan in plans {
            rollback_persisted_plan(
                &self.store,
                &plan,
                "Atlas restarted during this transaction. Exact before-state recovery ran automatically.",
            );
        }
    }

    fn discover_and_persist(&self) -> Result<ListDetectedGamesReply, Status> {
        let report = discover_games();
        let snapshot = self.query.latest_snapshot();
        let mut games = Vec::new();
        let store = self
            .store
            .lock()
            .map_err(|_| Status::internal("gaming store lock poisoned"))?;
        for game in report.games {
            let proto = discovered_to_proto(&game, snapshot.as_ref());
            let payload = StoredInstallPayload {
                limitations: proto.limitations.clone(),
            };
            let row = GameInstallRow {
                id: proto.id.clone(),
                catalog_id: proto.catalog_id.clone(),
                display_name: proto.display_name.clone(),
                platform: proto.platform,
                executable_path: proto.executable_path.clone(),
                executable_identity: proto.executable_identity.clone(),
                install_path: proto.install_path.clone(),
                version: proto.version.clone(),
                support_level: proto.support_level,
                last_seen_ms: proto.last_seen_ms,
                adapter_version: proto.adapter_version.clone(),
                payload_json: serde_json::to_string(&payload).map_err(internal)?,
            };
            store.upsert_game_install(&row).map_err(internal)?;
            games.push(proto);
        }
        let capabilities = report
            .capabilities
            .into_iter()
            .map(|cap| GamingCapability {
                id: cap.id.into(),
                name: launcher_name(cap.id),
                state: if cap.available && !cap.limited {
                    GamingCapabilityState::Available as i32
                } else if cap.limited {
                    GamingCapabilityState::Limited as i32
                } else {
                    GamingCapabilityState::Unavailable as i32
                },
                explanation: cap.explanation,
                limitations: Vec::new(),
            })
            .collect();
        Ok(ListDetectedGamesReply {
            games,
            capabilities,
            limitations: report.limitations,
            scanned_ms: report.scanned_ms,
        })
    }

    fn stored_game(&self, id: &str) -> Result<Option<GameInstall>, Status> {
        let store = self
            .store
            .lock()
            .map_err(|_| Status::internal("gaming store lock poisoned"))?;
        Ok(store
            .get_game_install(id)
            .map_err(internal)?
            .map(stored_install_to_proto))
    }

    fn readiness(&self, game: GameInstall, objective: GamingObjective) -> GamingReadiness {
        let captured_ms = now_ms();
        let device = device_info();
        let display = primary_display();
        let ac = power_is_ac();
        let battery = battery_status();
        let snapshot = self.query.latest_snapshot();
        let power_overlay = get_power_overlay_state();
        let running = game.running || game_is_running(&game, snapshot.as_ref());
        let frame_capture = PresentMonCapture::capability();

        let mut capabilities = vec![
            GamingCapability {
                id: "collector.game-discovery".into(), name: "Game discovery".into(),
                state: GamingCapabilityState::Available as i32,
                explanation: "Launcher manifests and verified pilot-game executable identities are available.".into(),
                limitations: vec!["Atlas does not crawl every file on every drive.".into()],
            },
            GamingCapability {
                id: "collector.frame-time".into(), name: "Frame-time capture".into(),
                state: if frame_capture.runnable {
                    GamingCapabilityState::ValidationRequired as i32
                } else {
                    GamingCapabilityState::Unavailable as i32
                },
                explanation: frame_capture.explanation,
                limitations: frame_capture.limitations,
            },
            GamingCapability {
                id: "collector.display-primary".into(), name: "Primary display mode".into(),
                state: if display.available { GamingCapabilityState::Limited as i32 } else { GamingCapabilityState::Unavailable as i32 },
                explanation: if display.available { format!("Windows reports {} × {} at {} Hz on the primary desktop.", display.width, display.height, display.refresh_hz) } else { display.limitation.clone() },
                limitations: vec![display.limitation.clone()],
            },
            GamingCapability {
                id: "collector.power-overlay".into(), name: "Power overlay".into(),
                state: if power_overlay.is_some() { GamingCapabilityState::Available as i32 } else { GamingCapabilityState::Unavailable as i32 },
                explanation: power_overlay.as_ref().map(|(_, label)| format!("The current Windows power overlay is {label}."))
                    .unwrap_or_else(|| "Windows did not expose the active power overlay, so Atlas cannot change it with exact rollback.".into()),
                limitations: Vec::new(),
            },
            GamingCapability {
                id: format!("adapter.{}", game.catalog_id), name: format!("{} configuration adapter", game.display_name),
                state: GamingCapabilityState::Limited as i32,
                explanation: "The installed executable is recognized, but configuration writes remain read-only until this exact game build passes round-trip fixtures.".into(),
                limitations: vec!["Unknown fields and encoding must be proven byte-preserving before writes are enabled.".into()],
            },
        ];
        if snapshot.is_none() {
            capabilities.push(GamingCapability {
                id: "collector.live-snapshot".into(),
                name: "Live system telemetry".into(),
                state: GamingCapabilityState::Unavailable as i32,
                explanation: "The service has not published its first system snapshot yet.".into(),
                limitations: Vec::new(),
            });
        } else {
            capabilities.push(GamingCapability {
                id: "collector.live-snapshot".into(), name: "Live system telemetry".into(),
                state: GamingCapabilityState::Available as i32,
                explanation: "CPU, GPU, memory, disk activity, process contention, and available GPU sensors are synchronized once per second.".into(), limitations: Vec::new(),
            });
        }

        let mut facts = vec![
            GamingFact { id: "os".into(), label: "Windows".into(), value: format!("{}.{}.{}", device.os_major, device.os_minor, device.os_build), explanation: "Read directly from the running Windows kernel version.".into(), state: GamingCapabilityState::Available as i32 },
            GamingFact { id: "cpu".into(), label: "CPU topology".into(), value: cpu_topology_text(&device), explanation: "Logical processor topology visible to Windows. Atlas does not guess BIOS settings.".into(), state: GamingCapabilityState::Available as i32 },
            GamingFact { id: "memory".into(), label: "Installed memory".into(), value: bytes_text(device.ram_total_bytes), explanation: "Physical memory visible to Windows. Configured DIMM speed and XMP/EXPO state are not proven by this collector.".into(), state: GamingCapabilityState::Limited as i32 },
            GamingFact { id: "display".into(), label: "Primary display".into(), value: if display.available { format!("{} × {} at {} Hz", display.width, display.height, display.refresh_hz) } else { "Unavailable".into() }, explanation: display.limitation.clone(), state: if display.available { GamingCapabilityState::Limited as i32 } else { GamingCapabilityState::Unavailable as i32 } },
            GamingFact { id: "power".into(), label: "Power state".into(), value: match ac { Some(true) => "Connected to external power".into(), Some(false) => "Running on battery".into(), None => "Not reported".into() }, explanation: if battery.available { format!("Battery {}%, {}.", battery.percent, if battery.charging { "charging" } else { "not charging" }) } else { battery.unavailable_reason.clone() }, state: if ac.is_some() { GamingCapabilityState::Available as i32 } else { GamingCapabilityState::Limited as i32 } },
            GamingFact { id: "game-state".into(), label: "Game process".into(), value: if running { "Running".into() } else { "Not running".into() }, explanation: "Configuration writes are always refused while the game is running.".into(), state: GamingCapabilityState::Available as i32 },
        ];
        if let Some(snapshot) = snapshot.as_ref() {
            let active = snapshot
                .gpu_adapters
                .iter()
                .find(|a| a.active_display)
                .or_else(|| snapshot.gpu_adapters.first());
            if let Some(gpu) = active {
                facts.push(GamingFact {
                    id: "gpu".into(),
                    label: "Active graphics adapter".into(),
                    value: gpu.name.clone(),
                    explanation: format!(
                        "Driver {}. Current dedicated-memory budget: {}.",
                        value_or_unknown(&gpu.driver_version),
                        bytes_text(gpu.dedicated_budget)
                    ),
                    state: GamingCapabilityState::Available as i32,
                });
                facts.push(GamingFact {
                    id: "gpu-sensors".into(),
                    label: "GPU sensors".into(),
                    value: if gpu.temperature_c.is_some() {
                        "Temperature available".into()
                    } else {
                        "Temperature unavailable".into()
                    },
                    explanation: if gpu.sensor_unavailable_reason.is_empty() {
                        "Sensor values come from the capability-labelled GPU provider.".into()
                    } else {
                        gpu.sensor_unavailable_reason.clone()
                    },
                    state: if gpu.temperature_c.is_some() {
                        GamingCapabilityState::Available as i32
                    } else {
                        GamingCapabilityState::Limited as i32
                    },
                });
            }
        }

        let context = RuleContext {
            device_build: device.os_build,
            refresh_hz: display.refresh_hz,
            display_available: display.available,
            ac,
            catalog_id: &game.catalog_id,
        };
        let findings = self
            .pack
            .rules
            .iter()
            .filter(|rule| rule_applies(rule, &context))
            .map(rule_to_finding)
            .collect::<Vec<_>>();
        let mut limitations = vec![
            "Windows cannot prove whether XMP or EXPO is enabled; Atlas reports only facts exposed by validated collectors.".into(),
            "HDR, VRR capability, monitor overdrive, DIMM slot details, storage health, and loaded network latency are not yet available in this build.".into(),
        ];
        limitations.extend(game.limitations.clone());
        let summary = if running {
            format!("{} is running. Atlas can record system evidence now; close the game before any supported configuration change.", game.display_name)
        } else {
            format!("{} is ready for a deterministic check. {} finding(s) explain what is known, what remains unknown, and what can be tested safely.", game.display_name, findings.len())
        };
        GamingReadiness {
            game: Some(GameInstall { running, ..game }),
            objective: objective as i32,
            captured_ms,
            capabilities,
            facts,
            findings,
            limitations,
            knowledge_pack_version: self.pack.version.clone(),
            summary,
        }
    }

    fn preview_plan(&self, game: GameInstall, objective: GamingObjective) -> GamingPlan {
        let readiness = self.readiness(game.clone(), objective);
        let config_hash = configuration_hash(&readiness);
        let mut steps = Vec::new();
        if let Some((_, label)) = get_power_overlay_state() {
            steps.push(GamingPlanStep {
                id: "safe.power-overlay".into(), order: 1,
                kind: GamingStepKind::PowerOverlay as i32,
                title: "Use best-performance power mode for the session".into(),
                explanation: "Atlas records the exact active overlay, applies the Windows best-performance overlay, verifies it immediately, and restores the original overlay when the plan is rolled back.".into(),
                before_value: label, after_value: "Best performance".into(),
                risk_lane: GamingRiskLane::AutomaticReversible as i32,
                selected: true, temporary: true, scope: "Current Windows user session".into(),
                restart_requirement: "None".into(), rollback: "Restore the exact recorded overlay GUID.".into(),
                verification: "Read the active overlay again and compare it with the requested GUID.".into(),
                preconditions: vec!["External power connected or desktop power state".into(), "Exact current overlay readable".into()],
                executable: true, action_key: "power.overlay.high".into(),
            });
        }
        for finding in &readiness.findings {
            if finding.action_key.is_empty()
                || finding.action_key == "none"
                || finding.action_key == "power.connect-charger"
            {
                continue;
            }
            let lane =
                GamingRiskLane::try_from(finding.risk_lane).unwrap_or(GamingRiskLane::GuidedManual);
            steps.push(GamingPlanStep {
                id: format!("finding.{}", finding.id),
                order: (steps.len() + 1) as u32,
                kind: if lane == GamingRiskLane::AdvancedExperiment {
                    GamingStepKind::GameConfiguration as i32
                } else {
                    GamingStepKind::GuidedChange as i32
                },
                title: finding.title.clone(),
                explanation: finding.why_it_matters.clone(),
                before_value: "Not verified".into(),
                after_value: finding.expected_benefit.clone(),
                risk_lane: lane as i32,
                selected: false,
                temporary: finding.temporary,
                scope: game.display_name.clone(),
                restart_requirement: finding.restart_requirement.clone(),
                rollback: finding.rollback.clone(),
                verification: finding.verification.clone(),
                preconditions: vec!["Game closed".into(), "Recognized adapter version".into()],
                executable: false,
                action_key: finding.action_key.clone(),
            });
        }
        steps.push(GamingPlanStep {
            id: "blocked.unsafe-tweaks".into(),
            order: (steps.len() + 1) as u32,
            kind: GamingStepKind::BlockedTweak as i32,
            title: "Unsafe tweak packs stay blocked".into(),
            explanation: format!(
                "The gaming planner cannot express these action types: {}.",
                self.pack.blocked_actions.join(", ")
            ),
            before_value: "Blocked by the action allowlist".into(),
            after_value: "No change".into(),
            risk_lane: GamingRiskLane::Blocked as i32,
            selected: false,
            temporary: false,
            scope: "System-wide".into(),
            restart_requirement: "Not applicable".into(),
            rollback: "No action can be executed.".into(),
            verification: "Negative allowlist tests assert these action keys cannot be prepared."
                .into(),
            preconditions: Vec::new(),
            executable: false,
            action_key: "blocked".into(),
        });
        let source_finding_ids = readiness
            .findings
            .iter()
            .map(|finding| finding.id.clone())
            .collect::<Vec<_>>();
        let plan_hash = plan_hash(&game.id, objective, &config_hash, &steps);
        GamingPlan {
            id: 0,
            plan_hash,
            configuration_snapshot_hash: config_hash,
            game_id: game.id,
            game_name: game.display_name,
            objective: objective as i32,
            status: GamingPlanStatus::Preview as i32,
            created_ms: now_ms(),
            expires_ms: 0,
            source_finding_ids,
            steps,
            checkpoint: "Preview only; no changes have been made.".into(),
            limitations: readiness.limitations,
        }
    }

    fn current_configuration_hash(
        &self,
        game_id: &str,
        objective: GamingObjective,
    ) -> Result<String, Status> {
        let game = self
            .stored_game(game_id)?
            .ok_or_else(|| Status::not_found("game install not found"))?;
        Ok(configuration_hash(&self.readiness(game, objective)))
    }

    fn load_plan(&self, id: i64) -> Result<Option<GamingPlan>, Status> {
        let store = self
            .store
            .lock()
            .map_err(|_| Status::internal("gaming store lock poisoned"))?;
        let Some(row) = store.get_gaming_plan(id).map_err(internal)? else {
            return Ok(None);
        };
        let step_rows = store.list_gaming_plan_steps(id).map_err(internal)?;
        let payload: StoredPlanPayload =
            serde_json::from_str(&row.payload_json).map_err(internal)?;
        let mut steps = Vec::new();
        for step in step_rows {
            let p: StoredStepPayload =
                serde_json::from_str(&step.payload_json).map_err(internal)?;
            steps.push(GamingPlanStep {
                id: step.step_id,
                order: step.ordinal,
                kind: step.kind,
                title: p.title,
                explanation: p.explanation,
                before_value: p.before_value,
                after_value: p.after_value,
                risk_lane: step.risk_lane,
                selected: step.selected,
                temporary: p.temporary,
                scope: p.scope,
                restart_requirement: p.restart_requirement,
                rollback: p.rollback,
                verification: p.verification,
                preconditions: p.preconditions,
                executable: step.executable,
                action_key: step.action_key,
            });
        }
        Ok(Some(GamingPlan {
            id: row.id,
            plan_hash: row.plan_hash,
            configuration_snapshot_hash: row.config_hash,
            game_id: row.game_id,
            game_name: payload.game_name,
            objective: row.objective,
            status: row.status,
            created_ms: row.created_ms,
            expires_ms: row.expires_ms,
            source_finding_ids: payload.source_finding_ids,
            steps,
            checkpoint: row.checkpoint,
            limitations: payload.limitations,
        }))
    }

    fn persist_plan(&self, mut plan: GamingPlan) -> Result<GamingPlan, Status> {
        let plan_payload = StoredPlanPayload {
            game_name: plan.game_name.clone(),
            source_finding_ids: plan.source_finding_ids.clone(),
            limitations: plan.limitations.clone(),
        };
        let row = GamingPlanRow {
            id: 0,
            plan_hash: plan.plan_hash.clone(),
            config_hash: plan.configuration_snapshot_hash.clone(),
            game_id: plan.game_id.clone(),
            objective: plan.objective,
            status: plan.status,
            created_ms: plan.created_ms,
            expires_ms: plan.expires_ms,
            checkpoint: plan.checkpoint.clone(),
            payload_json: serde_json::to_string(&plan_payload).map_err(internal)?,
        };
        let rows = plan
            .steps
            .iter()
            .map(|step| {
                let payload = StoredStepPayload {
                    title: step.title.clone(),
                    explanation: step.explanation.clone(),
                    before_value: step.before_value.clone(),
                    after_value: step.after_value.clone(),
                    temporary: step.temporary,
                    scope: step.scope.clone(),
                    restart_requirement: step.restart_requirement.clone(),
                    rollback: step.rollback.clone(),
                    verification: step.verification.clone(),
                    preconditions: step.preconditions.clone(),
                };
                Ok(GamingPlanStepRow {
                    plan_id: 0,
                    step_id: step.id.clone(),
                    ordinal: step.order,
                    kind: step.kind,
                    risk_lane: step.risk_lane,
                    selected: step.selected,
                    executable: step.executable,
                    action_key: step.action_key.clone(),
                    before_state_json: String::new(),
                    execution_status: "pending".into(),
                    payload_json: serde_json::to_string(&payload).map_err(internal)?,
                })
            })
            .collect::<Result<Vec<_>, Status>>()?;
        let mut store = self
            .store
            .lock()
            .map_err(|_| Status::internal("gaming store lock poisoned"))?;
        store
            .insert_gaming_config_snapshot(
                &plan.configuration_snapshot_hash,
                &plan.game_id,
                plan.created_ms,
                "{}",
            )
            .map_err(internal)?;
        plan.id = store.insert_gaming_plan(&row, &rows).map_err(internal)?;
        Ok(plan)
    }

    fn mint_token(&self, plan: &GamingPlan, sid: &str) -> String {
        let count = self.token_counter.fetch_add(1, Ordering::SeqCst);
        let mut hasher = Sha256::new();
        hasher.update(self.token_secret);
        hasher.update(plan.plan_hash.as_bytes());
        hasher.update(plan.configuration_snapshot_hash.as_bytes());
        hasher.update(sid.as_bytes());
        hasher.update(count.to_le_bytes());
        hasher.update(now_ms().to_le_bytes());
        hex(&hasher.finalize())
    }

    fn execute_plan(&self, token: PreparedToken) -> Result<ExecuteGamingPlanReply, Status> {
        let mut plan = self
            .load_plan(token.plan_id)?
            .ok_or_else(|| Status::not_found("prepared gaming plan not found"))?;
        if plan.plan_hash != token.plan_hash
            || plan.configuration_snapshot_hash != token.config_hash
        {
            return Err(Status::failed_precondition(
                "prepared plan identity no longer matches persisted state",
            ));
        }
        let objective = GamingObjective::try_from(plan.objective)
            .unwrap_or(GamingObjective::CompetitiveLatency);
        let current = self.current_configuration_hash(&plan.game_id, objective)?;
        if current != plan.configuration_snapshot_hash {
            return Err(Status::failed_precondition(
                "configuration changed after plan preparation; preview the plan again",
            ));
        }
        let game = self
            .stored_game(&plan.game_id)?
            .ok_or_else(|| Status::not_found("game install not found"))?;
        if game_is_running(&game, self.query.latest_snapshot().as_ref()) {
            return Err(Status::failed_precondition(
                "close the game before applying this plan",
            ));
        }

        plan.status = GamingPlanStatus::Applying as i32;
        plan.checkpoint = "Applying selected steps.".into();
        self.update_plan_record(&plan)?;
        let selected = plan
            .steps
            .iter()
            .filter(|step| step.selected)
            .cloned()
            .collect::<Vec<_>>();
        let mut completed = Vec::new();
        for step in selected {
            let result = match step.action_key.as_str() {
                "power.overlay.high" => self.execute_power_step(plan.id, &step),
                _ => Err(format!(
                    "action '{}' is not in the executable gaming allowlist",
                    step.action_key
                )),
            };
            match result {
                Ok(()) => completed.push(step.id.clone()),
                Err(detail) => {
                    // The current mutation may have succeeded before its
                    // verification failed. Include it in reverse recovery.
                    completed.push(step.id.clone());
                    let rollback_ok = self.rollback_completed(plan.id, &completed);
                    plan.status = GamingPlanStatus::Failed as i32;
                    plan.checkpoint = if rollback_ok {
                        format!("Apply stopped: {detail}. Completed steps were rolled back.")
                    } else {
                        format!("Apply stopped: {detail}. Rollback needs attention.")
                    };
                    self.update_plan_record(&plan)?;
                    return Ok(ExecuteGamingPlanReply {
                        success: false,
                        message: plan.checkpoint.clone(),
                        plan: Some(plan),
                    });
                }
            }
        }
        plan.status = GamingPlanStatus::Applied as i32;
        plan.checkpoint = "Selected safe steps were applied and verified. Record a comparable session, then Keep or Roll back.".into();
        self.update_plan_record(&plan)?;
        self.spawn_temporary_restore_monitor(&plan);
        Ok(ExecuteGamingPlanReply {
            success: true,
            message: plan.checkpoint.clone(),
            plan: Some(plan),
        })
    }

    fn spawn_temporary_restore_monitor(&self, plan: &GamingPlan) {
        if !plan
            .steps
            .iter()
            .any(|step| step.selected && step.temporary)
        {
            return;
        }
        let Ok(Some(game)) = self.stored_game(&plan.game_id) else {
            return;
        };
        let query = self.query.clone();
        let store = self.store.clone();
        let plan_id = plan.id;
        std::thread::spawn(move || {
            let deadline = now_ms().saturating_add(12 * 60 * 60 * 1_000);
            let mut game_seen = false;
            loop {
                let running = game_is_running(&game, query.latest_snapshot().as_ref());
                game_seen |= running;
                if (game_seen && !running) || now_ms() >= deadline {
                    break;
                }
                std::thread::sleep(Duration::from_secs(2));
            }
            let plan = store
                .lock()
                .ok()
                .and_then(|guard| guard.get_gaming_plan(plan_id).ok().flatten());
            if let Some(plan) = plan.filter(|plan| plan.status != GamingPlanStatus::Kept as i32) {
                rollback_persisted_plan(
                    &store,
                    &plan,
                    if game_seen {
                        "The game closed. Atlas restored every temporary action and verified the before-state."
                    } else {
                        "The temporary plan expired before the game started. Atlas restored and verified the before-state."
                    },
                );
            }
        });
    }

    fn execute_power_step(&self, plan_id: i64, step: &GamingPlanStep) -> Result<(), String> {
        let Some((guid, label)) = get_power_overlay_state() else {
            return Err("the current power overlay could not be read exactly".into());
        };
        let before = PowerBeforeState { guid, label };
        let before_json = serde_json::to_string(&before).map_err(|e| e.to_string())?;
        {
            let store = self
                .store
                .lock()
                .map_err(|_| "gaming store lock poisoned".to_string())?;
            store
                .update_gaming_step_state(plan_id, &step.id, &before_json, "applying")
                .map_err(|e| e.to_string())?;
            store
                .record_gaming_execution(
                    plan_id,
                    &step.id,
                    now_ms(),
                    "apply",
                    false,
                    "started",
                    &before_json,
                    "",
                )
                .map_err(|e| e.to_string())?;
        }
        let outcome = set_power_overlay("HighPerformance");
        if !outcome.success {
            return Err(outcome.message);
        }
        let verified =
            get_power_overlay_state().is_some_and(|(_, label)| label == "Best performance");
        let store = self
            .store
            .lock()
            .map_err(|_| "gaming store lock poisoned".to_string())?;
        store
            .record_gaming_execution(
                plan_id,
                &step.id,
                now_ms(),
                "verify",
                verified,
                if verified {
                    "best-performance overlay verified"
                } else {
                    "overlay verification failed"
                },
                &before_json,
                "Best performance",
            )
            .map_err(|e| e.to_string())?;
        store
            .update_gaming_step_state(
                plan_id,
                &step.id,
                &before_json,
                if verified {
                    "applied"
                } else {
                    "verification_failed"
                },
            )
            .map_err(|e| e.to_string())?;
        if verified {
            Ok(())
        } else {
            Err("Windows did not verify the requested power overlay".into())
        }
    }

    fn rollback_completed(&self, plan_id: i64, completed: &[String]) -> bool {
        let rows = match self
            .store
            .lock()
            .ok()
            .and_then(|store| store.list_gaming_plan_steps(plan_id).ok())
        {
            Some(rows) => rows,
            None => return false,
        };
        let mut ok = true;
        for step in rows
            .into_iter()
            .rev()
            .filter(|step| completed.iter().any(|id| id == &step.step_id))
        {
            ok &= rollback_step(&self.store, plan_id, &step);
        }
        ok
    }

    fn rollback_plan(&self, plan_id: i64) -> Result<RollbackGamingPlanReply, Status> {
        let mut plan = self
            .load_plan(plan_id)?
            .ok_or_else(|| Status::not_found("gaming plan not found"))?;
        plan.status = GamingPlanStatus::RollingBack as i32;
        plan.checkpoint = "Restoring exact before-state in reverse order.".into();
        self.update_plan_record(&plan)?;
        let rows = self
            .store
            .lock()
            .map_err(|_| Status::internal("gaming store lock poisoned"))?
            .list_gaming_plan_steps(plan_id)
            .map_err(internal)?;
        let mut success = true;
        for step in rows.into_iter().rev().filter(|step| {
            step.execution_status == "applied" || step.execution_status == "verification_failed"
        }) {
            success &= rollback_step(&self.store, plan_id, &step);
        }
        plan.status = if success {
            GamingPlanStatus::RolledBack as i32
        } else {
            GamingPlanStatus::Failed as i32
        };
        plan.checkpoint = if success {
            "The plan was rolled back and each restored value was verified.".into()
        } else {
            "One or more values could not be restored. Review the execution evidence before retrying.".into()
        };
        self.update_plan_record(&plan)?;
        Ok(RollbackGamingPlanReply {
            success,
            message: plan.checkpoint.clone(),
            plan: Some(plan),
        })
    }

    fn keep_plan(&self, plan_id: i64) -> Result<KeepGamingPlanReply, Status> {
        let mut plan = self
            .load_plan(plan_id)?
            .ok_or_else(|| Status::not_found("gaming plan not found"))?;
        if plan.status != GamingPlanStatus::Applied as i32 {
            return Ok(KeepGamingPlanReply {
                success: false,
                message: "Only an applied plan can be kept. Preview and apply a fresh plan first."
                    .into(),
                plan: Some(plan),
            });
        }
        plan.status = GamingPlanStatus::Kept as i32;
        plan.checkpoint = "The gamer chose Keep. Temporary restoration is disabled, but exact rollback state remains available.".into();
        self.update_plan_record(&plan)?;
        Ok(KeepGamingPlanReply {
            success: true,
            message: plan.checkpoint.clone(),
            plan: Some(plan),
        })
    }

    fn update_plan_record(&self, plan: &GamingPlan) -> Result<(), Status> {
        let payload = StoredPlanPayload {
            game_name: plan.game_name.clone(),
            source_finding_ids: plan.source_finding_ids.clone(),
            limitations: plan.limitations.clone(),
        };
        self.store
            .lock()
            .map_err(|_| Status::internal("gaming store lock poisoned"))?
            .update_gaming_plan_status(
                plan.id,
                plan.status,
                &plan.checkpoint,
                &serde_json::to_string(&payload).map_err(internal)?,
            )
            .map_err(internal)
    }

    fn session_proto(&self, row: &GameSessionRow) -> Result<GameSession, Status> {
        let game = self
            .stored_game(&row.game_id)?
            .map(|g| g.display_name)
            .unwrap_or_else(|| "Unknown game".into());
        let buckets = self
            .store
            .lock()
            .map_err(|_| Status::internal("gaming store lock poisoned"))?
            .list_game_trace_buckets(row.id, 20_000)
            .map_err(internal)?;
        Ok(session_from_rows(row, game, &buckets))
    }
}

#[tonic::async_trait]
impl AtlasGamingQuery for GamingService {
    async fn list_detected_games(
        &self,
        _request: Request<ListDetectedGamesRequest>,
    ) -> Result<Response<ListDetectedGamesReply>, Status> {
        Ok(Response::new(self.discover_and_persist()?))
    }

    async fn get_gaming_readiness(
        &self,
        request: Request<GetGamingReadinessRequest>,
    ) -> Result<Response<GetGamingReadinessReply>, Status> {
        let req = request.into_inner();
        let objective =
            GamingObjective::try_from(req.objective).unwrap_or(GamingObjective::CompetitiveLatency);
        let game = match self.stored_game(&req.game_id)? {
            Some(game) => game,
            None => {
                self.discover_and_persist()?;
                match self.stored_game(&req.game_id)? {
                    Some(game) => game,
                    None => {
                        return Ok(Response::new(GetGamingReadinessReply {
                            available: false,
                            unavailable_reason:
                                "The selected game installation is no longer available.".into(),
                            readiness: None,
                        }))
                    }
                }
            }
        };
        Ok(Response::new(GetGamingReadinessReply {
            available: true,
            unavailable_reason: String::new(),
            readiness: Some(self.readiness(game, objective)),
        }))
    }

    async fn list_game_sessions(
        &self,
        request: Request<ListGameSessionsRequest>,
    ) -> Result<Response<ListGameSessionsReply>, Status> {
        let req = request.into_inner();
        let rows = self
            .store
            .lock()
            .map_err(|_| Status::internal("gaming store lock poisoned"))?
            .list_game_sessions(&req.game_id, if req.limit == 0 { 50 } else { req.limit })
            .map_err(internal)?;
        let sessions = rows
            .iter()
            .map(|row| self.session_proto(row))
            .collect::<Result<Vec<_>, _>>()?;
        Ok(Response::new(ListGameSessionsReply { sessions }))
    }

    async fn get_game_session_trace(
        &self,
        request: Request<GetGameSessionTraceRequest>,
    ) -> Result<Response<GetGameSessionTraceReply>, Status> {
        let req = request.into_inner();
        let row = self
            .store
            .lock()
            .map_err(|_| Status::internal("gaming store lock poisoned"))?
            .get_game_session(req.session_id)
            .map_err(internal)?;
        let Some(row) = row else {
            return Ok(Response::new(GetGameSessionTraceReply {
                found: false,
                session: None,
                buckets: Vec::new(),
                limitations: Vec::new(),
            }));
        };
        let stored = self
            .store
            .lock()
            .map_err(|_| Status::internal("gaming store lock poisoned"))?
            .list_game_trace_buckets(
                row.id,
                if req.max_points == 0 {
                    3600
                } else {
                    req.max_points
                },
            )
            .map_err(internal)?;
        let buckets = stored.iter().map(trace_to_proto).collect();
        Ok(Response::new(GetGameSessionTraceReply {
            found: true,
            session: Some(self.session_proto(&row)?),
            buckets,
            limitations: vec![NO_FRAME_TIME_LIMITATION.into()],
        }))
    }

    async fn compare_game_sessions(
        &self,
        request: Request<CompareGameSessionsRequest>,
    ) -> Result<Response<CompareGameSessionsReply>, Status> {
        let req = request.into_inner();
        if req.baseline_session_ids.is_empty() || req.followup_session_ids.is_empty() {
            return Ok(Response::new(CompareGameSessionsReply {
                available: false,
                unavailable_reason: "Choose at least one baseline and one follow-up session."
                    .into(),
                comparison: None,
            }));
        }
        let mut baseline = Vec::new();
        let mut followup = Vec::new();
        for id in &req.baseline_session_ids {
            if let Some(row) = self
                .store
                .lock()
                .map_err(|_| Status::internal("gaming store lock poisoned"))?
                .get_game_session(*id)
                .map_err(internal)?
            {
                baseline.push(self.session_proto(&row)?);
            }
        }
        for id in &req.followup_session_ids {
            if let Some(row) = self
                .store
                .lock()
                .map_err(|_| Status::internal("gaming store lock poisoned"))?
                .get_game_session(*id)
                .map_err(internal)?
            {
                followup.push(self.session_proto(&row)?);
            }
        }
        if baseline.iter().chain(&followup).any(|s| {
            s.capture_quality != GamingCaptureQuality::FrameTimeValidated as i32 || !s.comparable
        }) {
            return Ok(Response::new(CompareGameSessionsReply { available: false, unavailable_reason: NO_FRAME_TIME_LIMITATION.into(), comparison: Some(GamingComparison { baseline_session_ids: req.baseline_session_ids, followup_session_ids: req.followup_session_ids, data_quality: GamingCaptureQuality::SystemOnly as i32, verdict: GamingComparisonVerdict::InsufficientEvidence as i32, explanation: "System telemetry alone cannot support an FPS or frame-time improvement claim.".into(), caveats: vec![NO_FRAME_TIME_LIMITATION.into()], ..GamingComparison::default() }) }));
        }
        let base = median(
            baseline
                .iter()
                .map(|s| {
                    s.summary
                        .as_ref()
                        .map(|x| x.frame_time_p50_ms)
                        .unwrap_or(0.0)
                })
                .collect(),
        );
        let next = median(
            followup
                .iter()
                .map(|s| {
                    s.summary
                        .as_ref()
                        .map(|x| x.frame_time_p50_ms)
                        .unwrap_or(0.0)
                })
                .collect(),
        );
        let effect = if base > 0.0 {
            (next - base) / base * 100.0
        } else {
            0.0
        };
        let verified = baseline.len() >= 3 && followup.len() >= 3;
        let verdict = if effect.abs() <= 5.0 {
            GamingComparisonVerdict::WithinNoise
        } else if effect < 0.0 && verified {
            GamingComparisonVerdict::VerifiedBetter
        } else if effect < 0.0 {
            GamingComparisonVerdict::ProvisionalBetter
        } else if verified {
            GamingComparisonVerdict::VerifiedWorse
        } else {
            GamingComparisonVerdict::ProvisionalWorse
        };
        Ok(Response::new(CompareGameSessionsReply {
            available: true,
            unavailable_reason: String::new(),
            comparison: Some(GamingComparison {
                baseline_session_ids: req.baseline_session_ids,
                followup_session_ids: req.followup_session_ids,
                baseline_median_frame_time_ms: base,
                followup_median_frame_time_ms: next,
                effect_percent: effect,
                noise_band_percent: 5.0,
                data_quality: GamingCaptureQuality::FrameTimeValidated as i32,
                verdict: verdict as i32,
                explanation: comparison_explanation(verdict, effect, verified),
                ..GamingComparison::default()
            }),
        }))
    }

    async fn preview_gaming_plan(
        &self,
        request: Request<PreviewGamingPlanRequest>,
    ) -> Result<Response<PreviewGamingPlanReply>, Status> {
        let req = request.into_inner();
        let objective =
            GamingObjective::try_from(req.objective).unwrap_or(GamingObjective::CompetitiveLatency);
        let game = self
            .stored_game(&req.game_id)?
            .ok_or_else(|| Status::not_found("game install not found"))?;
        Ok(Response::new(PreviewGamingPlanReply {
            available: true,
            unavailable_reason: String::new(),
            plan: Some(self.preview_plan(game, objective)),
        }))
    }
}

#[tonic::async_trait]
impl AtlasGamingControl for GamingService {
    async fn prepare_gaming_plan(
        &self,
        request: Request<PrepareGamingPlanRequest>,
    ) -> Result<Response<PrepareGamingPlanReply>, Status> {
        let sid = request
            .extensions()
            .get::<PipeConnectInfo>()
            .map(|info| info.client_sid.clone())
            .unwrap_or_default();
        if sid.is_empty() {
            return Err(Status::permission_denied(
                "the named-pipe client SID could not be verified",
            ));
        }
        let req = request.into_inner();
        let objective =
            GamingObjective::try_from(req.objective).unwrap_or(GamingObjective::CompetitiveLatency);
        let game = self
            .stored_game(&req.game_id)?
            .ok_or_else(|| Status::not_found("game install not found"))?;
        if game_is_running(&game, self.query.latest_snapshot().as_ref()) {
            return Ok(Response::new(PrepareGamingPlanReply {
                allowed: false,
                denial_reason: "Close the game before preparing a plan that can change settings."
                    .into(),
                plan: None,
                consent_token: String::new(),
                token_expires_ms: 0,
            }));
        }
        let mut plan = self.preview_plan(game, objective);
        if !req.selected_step_ids.is_empty() {
            for step in &mut plan.steps {
                step.selected = req.selected_step_ids.iter().any(|id| id == &step.id);
            }
        }
        if let Some(step) = plan.steps.iter().find(|step| {
            step.selected
                && (!step.executable
                    || step.risk_lane != GamingRiskLane::AutomaticReversible as i32)
        }) {
            return Ok(Response::new(PrepareGamingPlanReply { allowed: false, denial_reason: format!("'{}' is not an automatic reversible action. Run it as a controlled advanced or guided experiment instead.", step.title), plan: Some(plan), consent_token: String::new(), token_expires_ms: 0 }));
        }
        if !plan.steps.iter().any(|step| step.selected) {
            return Ok(Response::new(PrepareGamingPlanReply {
                allowed: false,
                denial_reason: "Select at least one automatic reversible step.".into(),
                plan: Some(plan),
                consent_token: String::new(),
                token_expires_ms: 0,
            }));
        }
        plan.status = GamingPlanStatus::Prepared as i32;
        plan.expires_ms = now_ms() + TOKEN_TTL_MS;
        plan.checkpoint =
            "Prepared from the current configuration. Consent expires in five minutes.".into();
        let plan = self.persist_plan(plan)?;
        let token = self.mint_token(&plan, &sid);
        self.tokens
            .lock()
            .map_err(|_| Status::internal("gaming token lock poisoned"))?
            .insert(
                token.clone(),
                PreparedToken {
                    plan_id: plan.id,
                    plan_hash: plan.plan_hash.clone(),
                    config_hash: plan.configuration_snapshot_hash.clone(),
                    client_sid: sid,
                    expires_ms: plan.expires_ms,
                },
            );
        Ok(Response::new(PrepareGamingPlanReply {
            allowed: true,
            denial_reason: String::new(),
            plan: Some(plan.clone()),
            consent_token: token,
            token_expires_ms: plan.expires_ms,
        }))
    }

    async fn execute_gaming_plan(
        &self,
        request: Request<ExecuteGamingPlanRequest>,
    ) -> Result<Response<ExecuteGamingPlanReply>, Status> {
        let sid = request
            .extensions()
            .get::<PipeConnectInfo>()
            .map(|info| info.client_sid.clone())
            .unwrap_or_default();
        let req = request.into_inner();
        let token = self
            .tokens
            .lock()
            .map_err(|_| Status::internal("gaming token lock poisoned"))?
            .remove(&req.consent_token)
            .ok_or_else(|| Status::permission_denied("consent token is invalid or already used"))?;
        if token.expires_ms < now_ms() {
            return Err(Status::permission_denied("consent token expired"));
        }
        if sid.is_empty() || sid != token.client_sid {
            return Err(Status::permission_denied(
                "consent token belongs to a different Windows user",
            ));
        }
        Ok(Response::new(self.execute_plan(token)?))
    }

    async fn rollback_gaming_plan(
        &self,
        request: Request<RollbackGamingPlanRequest>,
    ) -> Result<Response<RollbackGamingPlanReply>, Status> {
        let info = request
            .extensions()
            .get::<PipeConnectInfo>()
            .cloned()
            .unwrap_or_default();
        if info.client_sid.is_empty() {
            return Err(Status::permission_denied(
                "the named-pipe client SID could not be verified",
            ));
        }
        Ok(Response::new(
            self.rollback_plan(request.into_inner().plan_id)?,
        ))
    }

    async fn keep_gaming_plan(
        &self,
        request: Request<KeepGamingPlanRequest>,
    ) -> Result<Response<KeepGamingPlanReply>, Status> {
        let info = request
            .extensions()
            .get::<PipeConnectInfo>()
            .cloned()
            .unwrap_or_default();
        if info.client_sid.is_empty() {
            return Err(Status::permission_denied(
                "the named-pipe client SID could not be verified",
            ));
        }
        Ok(Response::new(self.keep_plan(request.into_inner().plan_id)?))
    }

    async fn start_gaming_session(
        &self,
        request: Request<StartGamingSessionRequest>,
    ) -> Result<Response<StartGamingSessionReply>, Status> {
        let req = request.into_inner();
        let objective =
            GamingObjective::try_from(req.objective).unwrap_or(GamingObjective::CompetitiveLatency);
        let game = self
            .stored_game(&req.game_id)?
            .ok_or_else(|| Status::not_found("game install not found"))?;
        let snapshot = self.query.latest_snapshot();
        let Some(process) = matching_process(&game, snapshot.as_ref()) else {
            return Ok(Response::new(StartGamingSessionReply {
                started: false,
                message: "Start the selected game before recording a session.".into(),
                session: None,
            }));
        };
        let process_id = process.pid;
        let process_create_time = process.create_time_100ns;
        let config_hash = self.current_configuration_hash(&game.id, objective)?;
        let start = now_ms();
        let frame_capability = PresentMonCapture::capability();
        let initial_payload = StoredSessionPayload {
            frame_summary: None,
            limitations: if frame_capability.runnable {
                vec![VALIDATION_LIMITATION.into()]
            } else {
                frame_capability.limitations.clone()
            },
        };
        let row = GameSessionRow {
            id: 0,
            game_id: game.id.clone(),
            objective: objective as i32,
            process_id,
            process_create_time,
            start_ms: start,
            end_ms: 0,
            capture_quality: GamingCaptureQuality::SystemOnly as i32,
            config_hash,
            applied_plan_id: req.applied_plan_id,
            comparable: false,
            payload_json: serde_json::to_string(&initial_payload).map_err(internal)?,
        };
        let id = self
            .store
            .lock()
            .map_err(|_| Status::internal("gaming store lock poisoned"))?
            .insert_game_session(&row)
            .map_err(internal)?;
        let stop = Arc::new(AtomicBool::new(false));
        let stop_thread = stop.clone();
        let query = self.query.clone();
        let store = self.store.clone();
        let game_thread = game.clone();
        let handle = std::thread::spawn(move || {
            collect_session_loop(
                query,
                store,
                game_thread,
                id,
                req.applied_plan_id,
                process_id,
                start,
                stop_thread,
            )
        });
        self.sessions
            .lock()
            .map_err(|_| Status::internal("gaming sessions lock poisoned"))?
            .insert(
                id,
                ActiveSession {
                    stop,
                    handle: Some(handle),
                },
            );
        let stored = self
            .store
            .lock()
            .map_err(|_| Status::internal("gaming store lock poisoned"))?
            .get_game_session(id)
            .map_err(internal)?
            .expect("inserted gaming session");
        let message = if frame_capability.runnable {
            "Recording system telemetry and attempting process-bound PresentMon FPS and frame times. If ETW permission is unavailable, Atlas will keep system evidence and report the frame gap instead of guessing."
        } else {
            "Recording synchronized system evidence. FPS capture is unavailable because the pinned PresentMon collector was not found or could not be verified."
        };
        Ok(Response::new(StartGamingSessionReply {
            started: true,
            message: message.into(),
            session: Some(self.session_proto(&stored)?),
        }))
    }

    async fn stop_gaming_session(
        &self,
        request: Request<StopGamingSessionRequest>,
    ) -> Result<Response<StopGamingSessionReply>, Status> {
        let id = request.into_inner().session_id;
        let mut active = self
            .sessions
            .lock()
            .map_err(|_| Status::internal("gaming sessions lock poisoned"))?
            .remove(&id);
        if let Some(session) = active.as_mut() {
            session.stop.store(true, Ordering::SeqCst);
            if let Some(handle) = session.handle.take() {
                let _ = handle.join();
            }
        }
        let row = self
            .store
            .lock()
            .map_err(|_| Status::internal("gaming store lock poisoned"))?
            .get_game_session(id)
            .map_err(internal)?;
        let Some(row) = row else {
            return Ok(Response::new(StopGamingSessionReply {
                stopped: false,
                message: "Session not found.".into(),
                session: None,
            }));
        };
        let session = self.session_proto(&row)?;
        let message = if session
            .summary
            .as_ref()
            .is_some_and(|summary| summary.average_fps > 0.0)
        {
            "Session stopped. Measured FPS and frame-time evidence is attached. It remains diagnostic until the validation gate passes."
        } else {
            "Session stopped. System evidence was saved, but no usable game-frame samples were captured."
        };
        Ok(Response::new(StopGamingSessionReply {
            stopped: true,
            message: message.into(),
            session: Some(session),
        }))
    }
}

struct RuleContext<'a> {
    device_build: u32,
    refresh_hz: u32,
    display_available: bool,
    ac: Option<bool>,
    catalog_id: &'a str,
}

fn rule_applies(rule: &KnowledgeRule, ctx: &RuleContext<'_>) -> bool {
    let catalog = rule
        .catalog_ids
        .iter()
        .any(|id| id == "*" || id == ctx.catalog_id);
    catalog
        && match rule.condition.as_str() {
            "always" | "frame_time_validation_required" => true,
            "primary_refresh_below_100" => {
                ctx.display_available && ctx.refresh_hz > 0 && ctx.refresh_hz < 100
            }
            "running_on_battery" => ctx.ac == Some(false),
            "windows_11_supported" => ctx.device_build >= 22_000,
            _ => false,
        }
}

fn rule_to_finding(rule: &KnowledgeRule) -> GamingFinding {
    GamingFinding {
        id: rule.id.clone(),
        severity: severity(&rule.severity) as i32,
        title: rule.title.clone(),
        observed: rule.observed.clone(),
        why_it_matters: rule.why_it_matters.clone(),
        evidence: format!(
            "Deterministic condition '{}' matched the current readiness snapshot.",
            rule.condition
        ),
        confidence: if rule.condition == "always" {
            "Moderate: installation is verified; the game setting is not yet readable.".into()
        } else {
            "High: the finding is based on a directly observed Windows fact.".into()
        },
        expected_benefit: rule.expected_benefit.clone(),
        tradeoff: rule.tradeoff.clone(),
        temporary: false,
        restart_requirement: rule.restart_requirement.clone(),
        rollback: rule.rollback.clone(),
        verification: rule.verification.clone(),
        limitations: Vec::new(),
        evidence_class: if rule.sources.is_empty() {
            GamingEvidenceClass::Observed as i32
        } else {
            GamingEvidenceClass::OfficialGuidance as i32
        },
        risk_lane: risk_lane(&rule.risk_lane) as i32,
        sources: rule
            .sources
            .iter()
            .map(|s| GamingSourceReference {
                title: s.title.clone(),
                uri: s.uri.clone(),
                publisher: s.publisher.clone(),
                reviewed_date: s.reviewed_date.clone(),
            })
            .collect(),
        action_key: rule.action_key.clone(),
    }
}

fn discovered_to_proto(game: &DiscoveredGame, snapshot: Option<&SnapshotReply>) -> GameInstall {
    GameInstall {
        id: game.id.clone(),
        catalog_id: game.catalog_id.clone(),
        display_name: game.display_name.clone(),
        platform: match game.platform {
            DiscoveredGamePlatform::Steam => GamePlatform::Steam,
            DiscoveredGamePlatform::Riot => GamePlatform::Riot,
            DiscoveredGamePlatform::Epic => GamePlatform::Epic,
            DiscoveredGamePlatform::Ea => GamePlatform::Ea,
            DiscoveredGamePlatform::BattleNet => GamePlatform::Battlenet,
            DiscoveredGamePlatform::Xbox => GamePlatform::Xbox,
            DiscoveredGamePlatform::Standalone => GamePlatform::Standalone,
        } as i32,
        executable_path: game.executable_path.to_string_lossy().into_owned(),
        executable_identity: game.executable_identity.clone(),
        install_path: game.install_path.to_string_lossy().into_owned(),
        version: game.version.clone(),
        support_level: match game.support_level {
            DiscoveredGameSupportLevel::Universal => GameSupportLevel::Universal,
            DiscoveredGameSupportLevel::PilotReadOnly => GameSupportLevel::PilotReadOnly,
            DiscoveredGameSupportLevel::PilotVersionGated => GameSupportLevel::PilotVersionGated,
        } as i32,
        last_seen_ms: game.last_seen_ms,
        adapter_version: game.adapter_version.clone(),
        running: game_is_running_path(&game.executable_path, snapshot),
        limitations: game.limitations.clone(),
    }
}

fn stored_install_to_proto(row: GameInstallRow) -> GameInstall {
    let limitations = serde_json::from_str::<StoredInstallPayload>(&row.payload_json)
        .map(|p| p.limitations)
        .unwrap_or_default();
    GameInstall {
        id: row.id,
        catalog_id: row.catalog_id,
        display_name: row.display_name,
        platform: row.platform,
        executable_path: row.executable_path,
        executable_identity: row.executable_identity,
        install_path: row.install_path,
        version: row.version,
        support_level: row.support_level,
        last_seen_ms: row.last_seen_ms,
        adapter_version: row.adapter_version,
        running: false,
        limitations,
    }
}

fn game_is_running(game: &GameInstall, snapshot: Option<&SnapshotReply>) -> bool {
    game_is_running_path(Path::new(&game.executable_path), snapshot)
}
fn game_is_running_path(path: &Path, snapshot: Option<&SnapshotReply>) -> bool {
    let name = path
        .file_name()
        .map(|x| x.to_string_lossy().into_owned())
        .unwrap_or_default();
    snapshot.is_some_and(|snap| {
        snap.processes
            .iter()
            .any(|p| p.image_name.eq_ignore_ascii_case(&name))
    })
}
fn matching_process<'a>(
    game: &GameInstall,
    snapshot: Option<&'a SnapshotReply>,
) -> Option<&'a ProcessRow> {
    let name = Path::new(&game.executable_path)
        .file_name()?
        .to_string_lossy();
    snapshot?
        .processes
        .iter()
        .find(|p| p.image_name.eq_ignore_ascii_case(&name))
}

fn configuration_hash(readiness: &GamingReadiness) -> String {
    let mut hasher = Sha256::new();
    hasher.update(
        readiness
            .game
            .as_ref()
            .map(|g| g.id.as_str())
            .unwrap_or_default()
            .as_bytes(),
    );
    hasher.update(readiness.objective.to_le_bytes());
    for fact in &readiness.facts {
        hasher.update(fact.id.as_bytes());
        hasher.update([0]);
        hasher.update(fact.value.as_bytes());
        hasher.update([0xff]);
    }
    hex(&hasher.finalize())
}

fn plan_hash(
    game_id: &str,
    objective: GamingObjective,
    config_hash: &str,
    steps: &[GamingPlanStep],
) -> String {
    let mut hasher = Sha256::new();
    hasher.update(game_id.as_bytes());
    hasher.update((objective as i32).to_le_bytes());
    hasher.update(config_hash.as_bytes());
    for step in steps {
        hasher.update(step.id.as_bytes());
        hasher.update(step.action_key.as_bytes());
        hasher.update([step.selected as u8]);
        hasher.update(step.before_value.as_bytes());
        hasher.update(step.after_value.as_bytes());
    }
    hex(&hasher.finalize())
}

fn rollback_step(store: &SharedStore, plan_id: i64, step: &GamingPlanStepRow) -> bool {
    let result = match step.action_key.as_str() {
        "power.overlay.high" => serde_json::from_str::<PowerBeforeState>(&step.before_state_json)
            .map_err(|e| e.to_string())
            .and_then(|before| {
                let outcome = restore_power_overlay_state(&before.guid);
                if !outcome.success {
                    return Err(outcome.message);
                }
                if get_power_overlay_state().is_some_and(|(guid, _)| guid == before.guid) {
                    Ok("power overlay restored and verified".to_string())
                } else {
                    Err("restored power overlay did not verify".into())
                }
            }),
        _ => Err(format!(
            "action '{}' has no rollback implementation",
            step.action_key
        )),
    };
    if let Ok(guard) = store.lock() {
        let success = result.is_ok();
        let detail = result.as_deref().unwrap_or_else(|e| e);
        let _ = guard.record_gaming_rollback(plan_id, &step.step_id, now_ms(), success, detail);
        let _ = guard.update_gaming_step_state(
            plan_id,
            &step.step_id,
            &step.before_state_json,
            if success {
                "rolled_back"
            } else {
                "rollback_failed"
            },
        );
    }
    result.is_ok()
}

fn collect_session_loop(
    query: Arc<QueryService>,
    store: SharedStore,
    game: GameInstall,
    session_id: i64,
    plan_id: i64,
    process_id: u32,
    started_ms: i64,
    stop: Arc<AtomicBool>,
) {
    let mut game_seen = false;
    let (mut frame_capture, mut frame_limitations) =
        match PresentMonCapture::start(process_id, session_id, started_ms) {
            Ok(capture) => (Some(capture), Vec::new()),
            Err(reason) => (None, vec![reason]),
        };
    while !stop.load(Ordering::SeqCst) {
        let now = now_ms();
        let bucket_ts = (now / 1_000) * 1_000;
        let snapshot = query.latest_snapshot();
        let running = game_is_running(&game, snapshot.as_ref());
        if running {
            game_seen = true;
        }
        if let Some(snapshot) = snapshot.as_ref() {
            let system = snapshot.system.as_ref();
            let gpu = snapshot
                .gpu_adapters
                .iter()
                .find(|g| g.active_display)
                .or_else(|| snapshot.gpu_adapters.first());
            let disk = snapshot
                .processes
                .iter()
                .map(|p| p.read_bps.saturating_add(p.write_bps))
                .sum();
            let game_count = snapshot
                .processes
                .iter()
                .filter(|p| matching_process(&game, Some(snapshot)).is_some_and(|m| m.pid == p.pid))
                .count();
            let bucket = GameTraceBucketRow {
                session_id,
                ts_ms: bucket_ts,
                frame_time_ms: 0.0,
                cpu_percent: system.map(|s| s.cpu_permille as f64 / 10.0).unwrap_or(0.0),
                gpu_percent: system.map(|s| s.gpu_permille as f64 / 10.0).unwrap_or(0.0),
                vram_used_bytes: system.map(|s| s.gpu_dedicated_used).unwrap_or(0),
                ram_used_bytes: system.map(|s| s.mem_used).unwrap_or(0),
                temperature_c: gpu.and_then(|g| g.temperature_c).unwrap_or(0.0),
                disk_bytes_per_sec: disk,
                background_processes: snapshot.processes.len().saturating_sub(game_count) as u32,
                incident: false,
                data_gap: false,
                event_label: if !game_seen {
                    "Waiting for game".into()
                } else {
                    String::new()
                },
            };
            if let Ok(guard) = store.lock() {
                let _ = guard.upsert_game_trace_bucket(&bucket);
            }
        } else if let Ok(guard) = store.lock() {
            let _ = guard.upsert_game_trace_bucket(&GameTraceBucketRow {
                session_id,
                ts_ms: bucket_ts,
                frame_time_ms: 0.0,
                cpu_percent: 0.0,
                gpu_percent: 0.0,
                vram_used_bytes: 0,
                ram_used_bytes: 0,
                temperature_c: 0.0,
                disk_bytes_per_sec: 0,
                background_processes: 0,
                incident: false,
                data_gap: true,
                event_label: "System snapshot unavailable".into(),
            });
        }
        if frame_capture
            .as_mut()
            .is_some_and(PresentMonCapture::enforce_raw_limit)
        {
            frame_limitations.push(
                "Atlas stopped raw frame collection at its bounded safety limit; system telemetry continued."
                    .into(),
            );
        }
        if game_seen && !running {
            break;
        }
        std::thread::sleep(Duration::from_secs(1));
    }

    let frame_result = frame_capture
        .take()
        .map(PresentMonCapture::finish)
        .unwrap_or_default();
    frame_limitations.extend(frame_result.limitations.clone());
    if let Ok(guard) = store.lock() {
        let existing = guard
            .list_game_trace_buckets(session_id, 200_000)
            .unwrap_or_default()
            .into_iter()
            .map(|bucket| (bucket.ts_ms, bucket))
            .collect::<HashMap<_, _>>();
        for frame in &frame_result.buckets {
            let mut bucket = existing
                .get(&frame.ts_ms)
                .cloned()
                .unwrap_or(GameTraceBucketRow {
                    session_id,
                    ts_ms: frame.ts_ms,
                    frame_time_ms: 0.0,
                    cpu_percent: 0.0,
                    gpu_percent: 0.0,
                    vram_used_bytes: 0,
                    ram_used_bytes: 0,
                    temperature_c: 0.0,
                    disk_bytes_per_sec: 0,
                    background_processes: 0,
                    incident: false,
                    data_gap: true,
                    event_label: "Frame evidence only; system sample unavailable".into(),
                });
            bucket.frame_time_ms = frame.frame_time_p95_ms;
            bucket.incident |= frame.incident;
            if frame.incident && !bucket.event_label.contains("Long-frame burst") {
                if !bucket.event_label.is_empty() {
                    bucket.event_label.push_str("; ");
                }
                bucket
                    .event_label
                    .push_str("Long-frame burst (50 ms or more)");
            }
            let _ = guard.upsert_game_trace_bucket(&bucket);
        }
        if let Ok(Some(mut row)) = guard.get_game_session(session_id) {
            row.end_ms = now_ms();
            if frame_result.summary.is_some() {
                row.capture_quality = GamingCaptureQuality::Partial as i32;
            }
            row.payload_json = serde_json::to_string(&StoredSessionPayload {
                frame_summary: frame_result.summary,
                limitations: deduplicate_strings(frame_limitations),
            })
            .unwrap_or_else(|_| "{}".into());
            let _ = guard.update_game_session(&row);
        }
    }
    if plan_id > 0 {
        let plan = store
            .lock()
            .ok()
            .and_then(|guard| guard.get_gaming_plan(plan_id).ok().flatten());
        if let Some(plan) = plan.filter(|plan| plan.status != GamingPlanStatus::Kept as i32) {
            rollback_persisted_plan(
                &store,
                &plan,
                "The recorded game session ended. Temporary actions were restored and verified.",
            );
        }
    }
}

fn rollback_persisted_plan(
    store: &SharedStore,
    plan: &GamingPlanRow,
    success_message: &str,
) -> bool {
    let steps = store
        .lock()
        .ok()
        .and_then(|guard| guard.list_gaming_plan_steps(plan.id).ok())
        .unwrap_or_default();
    let mut success = true;
    for step in steps.into_iter().rev().filter(|step| {
        matches!(
            step.execution_status.as_str(),
            "applying" | "applied" | "verification_failed" | "rollback_failed"
        )
    }) {
        success &= rollback_step(store, plan.id, &step);
    }
    if let Ok(guard) = store.lock() {
        let status = if success {
            GamingPlanStatus::RolledBack as i32
        } else {
            GamingPlanStatus::Failed as i32
        };
        let checkpoint = if success {
            success_message
        } else {
            "Automatic recovery could not verify every before-state. Review the rollback evidence."
        };
        let _ = guard.update_gaming_plan_status(plan.id, status, checkpoint, &plan.payload_json);
    }
    success
}

fn session_from_rows(
    row: &GameSessionRow,
    game_name: String,
    buckets: &[GameTraceBucketRow],
) -> GameSession {
    let count = buckets.len().max(1) as f64;
    let payload =
        serde_json::from_str::<StoredSessionPayload>(&row.payload_json).unwrap_or_default();
    let frame = payload.frame_summary.as_ref();
    let mut limitations = payload.limitations;
    if frame.is_none()
        && !limitations
            .iter()
            .any(|value| value == NO_FRAME_TIME_LIMITATION)
    {
        limitations.push(NO_FRAME_TIME_LIMITATION.into());
    }
    let mut contention = Vec::new();
    if buckets.iter().any(|bucket| bucket.cpu_percent >= 90.0) {
        contention.push("System CPU usage reached 90% or more during the session.".into());
    }
    if buckets.iter().any(|bucket| bucket.gpu_percent >= 95.0) {
        contention.push("GPU usage reached 95% or more during the session.".into());
    }
    let summary = GameSessionSummary {
        average_fps: frame.map(|value| value.average_fps).unwrap_or(0.0),
        one_percent_low_fps: frame.map(|value| value.one_percent_low_fps).unwrap_or(0.0),
        point_one_percent_low_fps: frame
            .map(|value| value.point_one_percent_low_fps)
            .unwrap_or(0.0),
        frame_time_p50_ms: frame.map(|value| value.frame_time_p50_ms).unwrap_or(0.0),
        frame_time_p95_ms: frame.map(|value| value.frame_time_p95_ms).unwrap_or(0.0),
        frame_time_p99_ms: frame.map(|value| value.frame_time_p99_ms).unwrap_or(0.0),
        long_frame_count: frame.map(|value| value.long_frame_count).unwrap_or(0),
        cpu_average_percent: buckets.iter().map(|b| b.cpu_percent).sum::<f64>() / count,
        gpu_average_percent: buckets.iter().map(|b| b.gpu_percent).sum::<f64>() / count,
        vram_peak_bytes: buckets.iter().map(|b| b.vram_used_bytes).max().unwrap_or(0),
        ram_peak_bytes: buckets.iter().map(|b| b.ram_used_bytes).max().unwrap_or(0),
        temperature_peak_c: buckets.iter().map(|b| b.temperature_c).fold(0.0, f64::max),
        contention,
        incidents: buckets
            .iter()
            .filter(|bucket| bucket.incident)
            .map(|bucket| format!("Long-frame burst near {}.", bucket.ts_ms))
            .collect(),
        limitations: limitations.clone(),
        ..GameSessionSummary::default()
    };
    GameSession {
        id: row.id,
        game_id: row.game_id.clone(),
        game_name,
        objective: row.objective,
        process_id: row.process_id,
        process_create_time_100ns: row.process_create_time,
        start_ms: row.start_ms,
        end_ms: row.end_ms,
        capture_quality: row.capture_quality,
        configuration_snapshot_hash: row.config_hash.clone(),
        applied_plan_id: row.applied_plan_id,
        summary: Some(summary),
        limitations,
        comparable: row.comparable,
    }
}

fn trace_to_proto(row: &GameTraceBucketRow) -> GamingTraceBucket {
    GamingTraceBucket {
        ts_ms: row.ts_ms,
        frame_time_ms: row.frame_time_ms,
        cpu_percent: row.cpu_percent,
        gpu_percent: row.gpu_percent,
        vram_used_bytes: row.vram_used_bytes,
        ram_used_bytes: row.ram_used_bytes,
        temperature_c: row.temperature_c,
        disk_bytes_per_sec: row.disk_bytes_per_sec,
        background_processes: row.background_processes,
        incident: row.incident,
        data_gap: row.data_gap,
        event_label: row.event_label.clone(),
    }
}
fn internal(error: impl std::fmt::Display) -> Status {
    Status::internal(error.to_string())
}
fn now_ms() -> i64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis()
        .min(i64::MAX as u128) as i64
}
fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}
fn launcher_name(id: &str) -> String {
    id.strip_prefix("launcher.")
        .map(|x| match x {
            "battlenet" => "Battle.net".into(),
            "ea" => "EA".into(),
            other => {
                let mut c = other.chars();
                c.next()
                    .map(|f| f.to_uppercase().collect::<String>() + c.as_str())
                    .unwrap_or_default()
            }
        })
        .unwrap_or_else(|| id.into())
}
fn severity(value: &str) -> GamingFindingSeverity {
    match value {
        "opportunity" => GamingFindingSeverity::Opportunity,
        "warning" => GamingFindingSeverity::Warning,
        "blocked" => GamingFindingSeverity::Blocked,
        _ => GamingFindingSeverity::Information,
    }
}
fn risk_lane(value: &str) -> GamingRiskLane {
    match value {
        "automatic" => GamingRiskLane::AutomaticReversible,
        "advanced" => GamingRiskLane::AdvancedExperiment,
        "blocked" => GamingRiskLane::Blocked,
        _ => GamingRiskLane::GuidedManual,
    }
}
fn value_or_unknown(value: &str) -> String {
    if value.is_empty() {
        "not reported".into()
    } else {
        value.into()
    }
}
fn bytes_text(bytes: u64) -> String {
    if bytes == 0 {
        "Not reported".into()
    } else {
        format!("{:.1} GB", bytes as f64 / 1_073_741_824.0)
    }
}
fn deduplicate_strings(values: Vec<String>) -> Vec<String> {
    let mut result = Vec::new();
    for value in values {
        if !value.is_empty() && !result.iter().any(|existing| existing == &value) {
            result.push(value);
        }
    }
    result
}
fn cpu_topology_text(device: &atlas_collectors::DeviceInfo) -> String {
    if device.heterogeneous {
        format!(
            "{} logical processors, {} performance cores, {} efficiency cores",
            device.logical_cpus, device.p_core_count, device.e_core_count
        )
    } else {
        format!("{} logical processors", device.logical_cpus)
    }
}
fn median(mut values: Vec<f64>) -> f64 {
    if values.is_empty() {
        return 0.0;
    }
    values.sort_by(f64::total_cmp);
    let n = values.len();
    if n % 2 == 0 {
        (values[n / 2 - 1] + values[n / 2]) / 2.0
    } else {
        values[n / 2]
    }
}
fn comparison_explanation(verdict: GamingComparisonVerdict, effect: f64, verified: bool) -> String {
    match verdict { GamingComparisonVerdict::WithinNoise => format!("The median changed by {:.1}%, which is inside the 5% run-to-run noise band.", effect), GamingComparisonVerdict::VerifiedBetter => format!("Three or more matched runs show a {:.1}% lower median frame time.", effect.abs()), GamingComparisonVerdict::VerifiedWorse => format!("Three or more matched runs show a {:.1}% higher median frame time.", effect.abs()), GamingComparisonVerdict::ProvisionalBetter => format!("One matched comparison is {:.1}% better. Run three comparable sessions before keeping the change.", effect.abs()), GamingComparisonVerdict::ProvisionalWorse => format!("One matched comparison is {:.1}% worse. Run three comparable sessions or roll back.", effect.abs()), _ => if verified { "The evidence is insufficient.".into() } else { "More comparable sessions are required.".into() } }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn knowledge_pack_is_versioned_and_conditions_are_allowlisted() {
        let pack: KnowledgePack = serde_json::from_str(KNOWLEDGE_JSON).expect("valid gaming pack");
        assert!(!pack.version.is_empty());
        assert!(pack.rules.iter().all(|rule| matches!(
            rule.condition.as_str(),
            "always"
                | "frame_time_validation_required"
                | "primary_refresh_below_100"
                | "running_on_battery"
                | "windows_11_supported"
        )));
    }

    #[test]
    fn blocked_actions_cannot_become_executable_keys() {
        let pack: KnowledgePack = serde_json::from_str(KNOWLEDGE_JSON).expect("valid gaming pack");
        assert!(pack
            .blocked_actions
            .contains(&"real-time-priority".to_string()));
        assert!(pack
            .rules
            .iter()
            .all(|rule| !pack.blocked_actions.contains(&rule.action_key)));
    }

    #[test]
    fn rocket_league_rules_are_bundled_and_remain_non_executable_guidance() {
        let pack: KnowledgePack = serde_json::from_str(KNOWLEDGE_JSON).expect("valid gaming pack");
        let rules = pack
            .rules
            .iter()
            .filter(|rule| rule.catalog_ids.iter().any(|id| id == "rocket-league"))
            .collect::<Vec<_>>();

        assert_eq!(rules.len(), 2);
        assert!(rules.iter().all(|rule| {
            matches!(rule.risk_lane.as_str(), "guided" | "advanced")
                && rule.action_key.starts_with("rocket-league.")
                && !rule.sources.is_empty()
        }));
    }

    #[test]
    fn comparison_noise_band_is_directionally_honest() {
        assert_eq!(median(vec![10.0, 12.0, 11.0]), 11.0);
        assert_eq!(median(vec![10.0, 12.0]), 11.0);
    }
}
