name: Release SBOM

on:
  release:
    types: [published]

permissions:
  actions: read
  contents: write

jobs:
  cyclonedx:
    name: Publish CycloneDX SBOM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event.release.tag_name }}
      - uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610 # v0
        with:
          path: .
          format: cyclonedx-json
          artifact-name: system-atlas-${{ github.event.release.tag_name }}.cdx.json
          output-file: system-atlas-${{ github.event.release.tag_name }}.cdx.json
          upload-artifact: true
          upload-release-assets: true
